stages:
  - deploy

variables:
  MAVEN_CLI_OPTS: "-B -e -V -DskipTests -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: maven
  paths:
    - .m2/repository

build:
  stage: deploy
  tags:
    - maven-deploy
  image: persipa/gitlab-runner-maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy