<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>site.persipa</groupId>
        <artifactId>persipa-spring-parent</artifactId>
        <version>1.0.3</version>
        <relativePath/>
    </parent>

    <artifactId>persipa-cloud-common</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>persipa-cloud-common</name>

    <properties>
        <revision>4.2.0-SNAPSHOT</revision>
    </properties>

    <modules>
        <module>persipa-cloud-common-core</module>
        <module>persipa-cloud-common-spring-boot-starter</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
